apiVersion: skaffold/v3
kind: Config
metadata:
  name: company-cursor-party
build:
  artifacts:
    - image: gcr.io/company-cursor-party/ws
      docker:
        dockerfile: ws/Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev
deploy:
  kubeContext: minikube
  kubectl:
    defaultNamespace: company-cursor-party
profiles:
  - name: microk8s
    deploy:
      kubeContext: microk8s
    build:
      local:
        push: true
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: localhost:32000/company-cursor-party-ws
      - op: replace
        path: /manifests/kustomize/paths
        value:
          - k8s/overlays/microk8s
# Important! When you're using minikube run `minikube tunnel` to expose the services.

# use dev context
# kubectl config use-context minikube

# use microk8s context
# kubectl config use-context microk8s

# deploy
# skaffold run -p microk8s
